--1. UUID data type

/*
1. UUID Universal Unique Identifier

2. It is a 128-bit quantity generated by an algorithimn that make it a unique in the known 
universe using the same algorithmn.

3. Example 

	40e6215d-076g-4896-987c-f30f3678f608

	- 32 digits
	- hexadecimal digits 
	- separated by hyphens

4. UUID is much better than a data type when it comes to uniqueness across systems as SERIAL data
type generates only unique values within a single database

5. To create a UUID data type in PostgreSQL, you need a third part UUID algorithmns to generate
UUID e.g. uuid-ossp
*/

-- 1. Enable third part UUID extensions first e.g. uuid-ossp

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Lets generate a sample UUID value first

SELECT uuid_generate_v1();
-- v4 generate purely random characters, while v1 combines mac address, time with random numbers
-- to generate the uuid
SELECT uuid_generate_v4()

-- 3. Lets create a sample table 'table_uuid'

CREATE TABLE table_uuid(
	product_id UUID DEFAULT uuid_generate_v1(),
	product_name VARCHAR(100) NOT NULL
)
-- 4. Lets view the data in the sample table

SELECT * FROM table_uuid

-- 5. Lets insert some data into table_uuid

INSERT INTO table_uuid(product_name)
VALUES
('Iphone 16 Pro Max'),
('Dell Alienware Area 51'),
('Macbook Pro M5');


-- 6. Lets change UUID  default value
ALTER table table_uuid
ALTER COLUMN product_id
SET DEFAULT uuid_generate_v4();












